### ISSUE TITLE
Lab 0: Establish Remote Working Env

### ISSUE THREAD

**Issue by pburkholder** [devopsdc/intro2devops#6]

**Comment by pburkholder** [comment]
Lab 0 has been released. Comments here please.

**Comment by chershchef** [comment]
Lab 0 
Pros
-Iit worked great! I had no issues on the Linux version and it made sense. 
-I like the step by step; nothing was missing in setting this up and executing it
-I like the screenshots and boxes highlighting what the output should look like
Suggestions:
-The interface of Nano might be a bit confusing for some, maybe use vi? Maybe that's more confusing...your call.

**Comment by chershchef** [comment]
Lab 1
Pros
-I love the "oops" section; great idea! 
-I love the Linux tips like using the up arrow to repeat commands
-the fortunes are clever and are a good way to keep people engaged
-I got an error removing fortune, pasted below Suggestions

Suggestions
-A:Again, Again section for fortunes, is that supposed to be a different script or the same as A:Try it Out
-Systems can drift: are you going to elaborate on this? As a newbie DevOps or Linux person I wouldn't know what drift means without context. Maybe that's not your audience.
-B:Chef Apply you could add a Linux tip about the exclamation mark repeating commands, like !nano to pull up editing the same file
-B: Just for Fun the very last block says [s1]... which is not the output for [ls], is that a typo?

# Fortune error

alpha@ip-10-45-189-12:~$ chef-apply -e 'package "fortune-mod" do; action(:remove); end'
Recipe: (chef-apply cookbook)::(chef-apply recipe)
- apt_package[fortune-mod] action remove
  
  # 
  
  # Error executing action `remove` on resource 'apt_package[fortune-mod]'
  
  ## Mixlib::ShellOut::ShellCommandFailed
  
  Expected process to exit with [0], but received '100'
  ---- Begin output of apt-get -q -y remove fortune-mod ----
  STDOUT:
  STDERR: E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
  E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?
  ---- End output of apt-get -q -y remove fortune-mod ----
  Ran apt-get -q -y remove fortune-mod returned 100
  
  ## Resource Declaration:
  
  # In /tmp/recipe-temporary-file20150515-16594-yg7lzx
  
    1: package "fortune-mod" do; action(:remove); end
  
  ## Compiled Resource:
  
  # Declared in /tmp/recipe-temporary-file20150515-16594-yg7lzx:1:in `run_chef_recipe'
  
  apt_package("fortune-mod") do
    action [:remove]
    retries 0
    retry_delay 2
    default_guard_interpreter :default
    package_name "fortune-mod"
    timeout 900
    declared_type :package
    cookbook_name "(chef-apply cookbook)"
    recipe_name "(chef-apply recipe)"
  end

[2015-05-15T20:28:59+00:00] FATAL: Stacktrace dumped to /home/alpha/.chef/cache/chef-stacktrace.out
[2015-05-15T20:28:59+00:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: apt_package[fortune-mod](%28chef-apply cookbook%29::%28chef-apply recipe%29 line 1) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '100'
---- Begin output of apt-get -q -y remove fortune-mod ----
STDOUT:
STDERR: E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?
---- End output of apt-get -q -y remove fortune-mod ----
Ran apt-get -q -y remove fortune-mod returned 100

**Comment by pburkholder** [comment]
Thanks so much for you comments, @chershchef.  Looks like I missed a 'sudo' with the package removal.

I'm not much of a fan of Nano but Vi requires learning to navigate between modes, and I couldn't get the Atom remote-sync plugin working consistently.
